---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 125
  Exclude:
    - 'lib/gitlab/client/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/gitlab/*'
    - 'lib/gitlab/client/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/gitlab/file_response_spec.rb'
    - 'spec/gitlab/help_spec.rb'
